### ISSUE TITLE
Trigonometry Utils

### ISSUE THREAD

**Issue by eshira** [MOARbots/wixel-sdk#5]
Write the Wixel appropriate version of the following trig utils:
- Angle between two points
- Choose clockwise or counterclockwise turn given robot heading and desired robot heading

**Comment by shavlik** [comment]
The first of these is in the s/w in the math library for our C.
See atan2, which handles the four quadrants properly
(http://en.m.wikipedia.org/wiki/Atan2)

The second just needs subtraction and comparison to 0.

Be sure to convert between radians and degrees (I sent email containing code for this last week).

  Jude

**Comment by amcolash** [comment]
I am working on an implementation for sdcc, as my last was for c so slightly different. Will be testing tonight. Using atan2 should be exactly what we need though to compare whether to turn left/right as Jude pointed out
