### ISSUE TITLE
Debug sendReportRadio/USB

### ISSUE THREAD

**Issue by eshira** [MOARbots/wixel-sdk#7]
Seems to overflow buffer and write into program memory. Fix requested.

**Comment by erinzm** [comment]
Once I get the reporting lib to work, I'm going to add a bounds check in `putchar(`**`char c`**`)`, and just discard data or wrap it to the beginning of the `char[]` array.

**Comment by eshira** [comment]
I added a bounds check to putchar locally, tried a few things out, but I think implementing a proper circular buffer here would be a better approach. The way the code is set up right now is frustrating to read anyway.
